### PR TITLE
Update BulkProjection.R

### PR DESCRIPTION
**Pull request by jacob-greene**
Found a bug in Bulk Projection function.

### CODE REVIEW

**Comment by rcorces** [comment]
Thanks for posting. This line would indeed cause an error if the first indexed feature were used in the LSI, causing that expression to evaluate to a divide by 0.
I dont think the solution is to remove the -1 though because this leads to the widths not being correct. I need to think about edge cases but I believe that the width could also just be set to `rD$tileSize` instead.

**Comment by rcorces** [comment]
I think I've solved this bug on the `dev` branch via https://github.com/GreenleafLab/ArchR/commit/41fb8bb1db86e0d4ac669c4f55918bdb0b689c30
I'm going to close this pull request but please let me know if I've mis-interpreted the bug you were fixing or if the implemented solution does not seem to fix the problem. Thanks for bringing this up.

**Comment by jacob-greene** [comment]
Thanks for following up on this! I don’t have time to test this for myself currently, but will circle back later. I used this function to validate a single-cell CUT&Tag method by projecting ChIP-seq, and my patch seemed to work, so I sent it your way. Hopefully your fix makes it more reproducible for everyone.On Jan 3, 2023, at 5:52 AM, Ryan Corces ***@***.***> wrote:﻿
I think I've solved this bug on the dev branch via 41fb8bb
I'm going to close this pull request but please let me know if I've mis-interpreted the bug you were fixing or if the implemented solution does not seem to fix the problem. Thanks for bringing this up.

**Comment by jacob-greene** [comment]
Hey,

I gave your patch a shot and it didn’t work for me. Of note, I’m binning my data, and so far this has only worked by removing the -1.

Best,
Jacob
—
Jacob E. Greene, M.A.
Graduate Student
Steven Henikoff Lab, HHMI/Fred Hutchinson Cancer Center
Molecular Medicine (M3D) PhD Program, University of Washington
***@***.******@***.***> | ***@***.******@***.***> | 206-303-0052

On Jan 3, 2023, at 9:02 AM, Jacob Greene ***@***.******@***.***>> wrote:

Thanks for following up on this! I don’t have time to test this for myself currently, but will circle back later. I used this function to validate a single-cell CUT&Tag method by projecting ChIP-seq, and my patch seemed to work, so I sent it your way. Hopefully your fix makes it more reproducible for everyone.

On Jan 3, 2023, at 5:52 AM, Ryan Corces ***@***.******@***.***>> wrote:

﻿


I think I've solved this bug on the dev branch via 41fb8bb<https://github.com/GreenleafLab/ArchR/commit/41fb8bb1db86e0d4ac669c4f55918bdb0b689c30>
I'm going to close this pull request but please let me know if I've mis-interpreted the bug you were fixing or if the implemented solution does not seem to fix the problem. Thanks for bringing this up.

**Comment by rcorces** [comment]
thanks for following up @jacob-greene . Do you happen to have the error that it gave you when you tried using the new code?

**Comment by jacob-greene** [comment]
Hi Ryan,

Here’s the log file I get from your patch (ArchR-projectBulkATAC-75052002ed89-Date-2023-01-20_Time-10-11-33.log) and my patch  (ArchR-projectBulkATAC-6fc017ea8986-Date-2023-01-19_Time-23-38-09.log). Let me know if you need anything else!

Best,
Jacob


—
Jacob E. Greene, M.A.
Graduate Student
Steven Henikoff Lab, HHMI/Fred Hutchinson Cancer Center
Molecular Medicine (M3D) PhD Program, University of Washington
***@***.*** | ***@***.*** | 206-303-0052

**Comment by jacob-greene** [comment]
How about this:
[ArchR-projectBulkATAC-6fc017ea8986-Date-2023-01-19_Time-23-38-09.log](https://github.com/GreenleafLab/ArchR/files/10471273/ArchR-projectBulkATAC-6fc017ea8986-Date-2023-01-19_Time-23-38-09.log)
[ArchR-projectBulkATAC-75052002ed89-Date-2023-01-20_Time-10-11-33.log](https://github.com/GreenleafLab/ArchR/files/10471274/ArchR-projectBulkATAC-75052002ed89-Date-2023-01-20_Time-10-11-33.log)

**Comment by rcorces** [comment]
Sorry - I know this is a little stale but I still havent figured out why my proposed fix didnt work for you. I'm nearly positive that you are hitting a divide by zero issue and I really thought that my previous fix would have solved the problem.

Would it be possible for you to email me an R object file with your reduced dims object? You can send it to archr.devs@gmail.com
```
rD <- getReducedDims(ArchRProj, reducedDims = reducedDims, returnMatrix = FALSE)
saveRDS(object = rD, file = "rD.rds")
```

**Comment by rcorces** [comment]
Thanks for providing the `rD` object via email. Is it possible that when you tested out the `dev` branch that the actual ArchR codebase didnt get updated. For ex. you have to force detach the package and reload it or restart your R session or the new install wont be loaded.

the Features part of your `rD` object looks like this:
```
> rD[[grep("Features", names(rD))]]
DataFrame with 60630 rows and 4 columns
      seqnames       idx   rowSums     start
         <Rle> <integer> <numeric> <numeric>
1         chr1         1         0         0
2         chr1         2         0     50000
3         chr1         3         0    100000
4         chr1         4         0    150000
5         chr1         5         0    200000
...        ...       ...       ...       ...
60626     chrX      3117      1595 155800000
60627     chrX      3118      1333 155850000
60628     chrX      3119       486 155900000
60629     chrX      3120         0 155950000
60630     chrX      3121         0 156000000
```

Your error was occurring during the process of creating the `rDGR` object. This must be the case because your logfile ends prematurely before the `rDGR` object is logged. Originally, that code to create `rDGR` looked like this:
https://github.com/GreenleafLab/ArchR/blob/79953a93ae376a500e681aa3b5ba669af6bb58e1/R/BulkProjection.R#L46-L54

Specifically, Line 53 was causing problems because `rDFeatures$idx - 1` evaluates to `0` if `idx = 1` and this results in a divide by zero (`NaN`) for the first element in your rDFeatures:
```
> head((rDFeatures$start) / (rDFeatures$idx - 1))
[1]   NaN 50000 50000 50000 50000 50000
```
```
> GRanges(seqnames=rDFeatures$seqnames,IRanges(start=rDFeatures$start, width = (rDFeatures$start) / (rDFeatures$idx - 1)))
Error in .new_IRanges_from_start_width(start, width) : 
  'start' or 'width' cannot contain NAs
```

If instead you use the code in my fix, you can successfully create an `rDGR` object that looks like this:
```
> GRanges(seqnames=rDFeatures$seqnames,IRanges(start=rDFeatures$start, width = rD$tileSize))
GRanges object with 60630 ranges and 0 metadata columns:
          seqnames              ranges strand
             <Rle>           <IRanges>  <Rle>
      [1]     chr1             0-49999      *
      [2]     chr1         50000-99999      *
      [3]     chr1       100000-149999      *
      [4]     chr1       150000-199999      *
      [5]     chr1       200000-249999      *
      ...      ...                 ...    ...
  [60626]     chrX 155800000-155849999      *
  [60627]     chrX 155850000-155899999      *
  [60628]     chrX 155900000-155949999      *
  [60629]     chrX 155950000-155999999      *
  [60630]     chrX 156000000-156049999      *
  -------
  seqinfo: 23 sequences from an unspecified genome; no seqlengths
```

This is different from the object created with your fix which looks like this:
```
> GRanges(seqnames=rDFeatures$seqnames,IRanges(start=rDFeatures$start, width = (rDFeatures$start) / (rDFeatures$idx)))
GRanges object with 60630 ranges and 0 metadata columns:
          seqnames              ranges strand
             <Rle>           <IRanges>  <Rle>
      [1]     chr1                0--1      *
      [2]     chr1         50000-74999      *
      [3]     chr1       100000-133332      *
      [4]     chr1       150000-187499      *
      [5]     chr1       200000-239999      *
      ...      ...                 ...    ...
  [60626]     chrX 155800000-155849982      *
  [60627]     chrX 155850000-155899982      *
  [60628]     chrX 155900000-155949982      *
  [60629]     chrX 155950000-155999982      *
  [60630]     chrX 156000000-156049982      *
  -------
  seqinfo: 23 sequences from an unspecified genome; no seqlengths
```
 You'll notice that the widths are not constant, which is not correct for a `TileMatrix` input:

```
> length(unique(width(GRanges(seqnames=rDFeatures$seqnames,IRanges(start=rDFeatures$start, width = (rDFeatures$start) / (rDFeatures$idx))))))
[1] 437
```

I have a feeling that something just went wrong when you tried to run the `dev` branch. Is that possible? This is the safest way to ensure that the newly installed version is properly loaded:

```
devtools::install_github("GreenleafLab/ArchR", ref="dev", repos = BiocManager::repositories(), upgrade = "never")
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)
```

**Comment by jacob-greene** [comment]
Yeah it’s possible I didn’t install correctly, but all I did was mv the directory to rename it and install the dev branch. I do use renv, so maybe that messed things up. Anyway, glad your fix works! Seems like we’re set. Of note, the paper we just submitted is a nature protocols for doing single-cell combinatorial indexing CUT&Tag. For analysis we really like using ArchR, so thanks for making such a versatile tool. If there are any novel analyses you’d be curious to try for single-cell CUT&Tag, it would be fun to collaborate. If this interests you or you’d like to hear what we have in the works let me know!Best,JacobOn Feb 4, 2023, at 2:45 PM, Ryan Corces ***@***.***> wrote:﻿
Thanks for providing the rD object via email. Is it possible that when you tested out the dev branch that the actual ArchR codebase didnt get updated. For ex. you have to force detach the package and reload it or restart your R session or the new install wont be loaded.
the Features part of your rD object looks like this:
> rD[[grep("Features", names(rD))]]
DataFrame with 60630 rows and 4 columns
      seqnames       idx   rowSums     start
         <Rle> <integer> <numeric> <numeric>
1         chr1         1         0         0
2         chr1         2         0     50000
3         chr1         3         0    100000
4         chr1         4         0    150000
5         chr1         5         0    200000
...        ...       ...       ...       ...
60626     chrX      3117      1595 155800000
60627     chrX      3118      1333 155850000
60628     chrX      3119       486 155900000
60629     chrX      3120         0 155950000
60630     chrX      3121         0 156000000

Your error was occurring during the process of creating the rDGR object. This must be the case because your logfile ends prematurely before the rDGR object is logged. Originally, that code to create rDGR looked like this:
https://github.com/GreenleafLab/ArchR/blob/79953a93ae376a500e681aa3b5ba669af6bb58e1/R/BulkProjection.R#L46-L54
Specifically, Line 53 was causing problems because rDFeatures$idx - 1 evaluates to 0 if idx = 1 and this results in a divide by zero (NaN) for the first element in your rDFeatures:
> head((rDFeatures$start) / (rDFeatures$idx - 1))
[1]   NaN 50000 50000 50000 50000 50000

> GRanges(seqnames=rDFeatures$seqnames,IRanges(start=rDFeatures$start, width = (rDFeatures$start) / (rDFeatures$idx - 1)))
Error in .new_IRanges_from_start_width(start, width) : 
  'start' or 'width' cannot contain NAs

If instead you use the code in my fix, you can successfully create an rDGR object that looks like this:
> GRanges(seqnames=rDFeatures$seqnames,IRanges(start=rDFeatures$start, width = rD$tileSize))
GRanges object with 60630 ranges and 0 metadata columns:
          seqnames              ranges strand
             <Rle>           <IRanges>  <Rle>
      [1]     chr1             0-49999      *
      [2]     chr1         50000-99999      *
      [3]     chr1       100000-149999      *
      [4]     chr1       150000-199999      *
      [5]     chr1       200000-249999      *
      ...      ...                 ...    ...
  [60626]     chrX 155800000-155849999      *
  [60627]     chrX 155850000-155899999      *
  [60628]     chrX 155900000-155949999      *
  [60629]     chrX 155950000-155999999      *
  [60630]     chrX 156000000-156049999      *
  -------
  seqinfo: 23 sequences from an unspecified genome; no seqlengths

This is different from the object created with your fix which looks like this:
> GRanges(seqnames=rDFeatures$seqnames,IRanges(start=rDFeatures$start, width = (rDFeatures$start) / (rDFeatures$idx)))
GRanges object with 60630 ranges and 0 metadata columns:
          seqnames              ranges strand
             <Rle>           <IRanges>  <Rle>
      [1]     chr1                0--1      *
      [2]     chr1         50000-74999      *
      [3]     chr1       100000-133332      *
      [4]     chr1       150000-187499      *
      [5]     chr1       200000-239999      *
      ...      ...                 ...    ...
  [60626]     chrX 155800000-155849982      *
  [60627]     chrX 155850000-155899982      *
  [60628]     chrX 155900000-155949982      *
  [60629]     chrX 155950000-155999982      *
  [60630]     chrX 156000000-156049982      *
  -------
  seqinfo: 23 sequences from an unspecified genome; no seqlengths

You'll notice that the widths are not constant, which is not correct for a TileMatrix input:
> length(unique(width(GRanges(seqnames=rDFeatures$seqnames,IRanges(start=rDFeatures$start, width = (rDFeatures$start) / (rDFeatures$idx))))))
[1] 437

I have a feeling that something just went wrong when you tried to run the dev branch. Is that possible? This is the safest way to ensure that the newly installed version is properly loaded:
devtools::install_github("GreenleafLab/ArchR", ref="dev", repos = BiocManager::repositories(), upgrade = "never")
#to unload a package and reload
detach("package:ArchR", unload=TRUE)
library(ArchR)

**Comment by rcorces** [comment]
Glad you guys have enjoyed using ArchR. I'll admit that our bandwidth for adding new features is a bit thin but I'd be happy to chat any time to learn more about what you all are doing and what types of things might best support ongoing and future work. You can find my work email on my lab's website (www.corceslab.com).

**Pull request closed without merging**
